# Generated by Django 2.1.5 on 2020-11-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Competence', '0002_auto_20201104_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compentence',
            name='user',
        ),
    ]
